# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - n8n-pg-user.enc.yaml
  - n8n-secret.enc.yaml
  - cluster-cnpg.yaml
  - pvc.yaml
  - ocirepository.yaml
  - helmrelease.yaml
