apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
    namespace: n8n
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:SP1i0KW5XBixi+b4xAvGxpmbM+R4Dy/P4+zD4Zq9G2h0RfXqxFrXKEgN8YmoCYsL,iv:/iC42c+68vHhzkWxcVEJRnzrLXruy0qQkuSw/Hl8PbA=,tag:HjnebXSA4cavQT0uK4Ne6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByK3FzYnlXZXJYaG55Yjhv
            S2FtbWI1cXpqalBQaWx4RllqNGdydUlJQTJZClhra09XOU9nRUowVVdyTUNZQnZx
            M2dFVEZ5UG9ISUJPOEJVMkttRlFoN0EKLS0tIE83YmZ1ZnZncDZ3WTBrUkIwRS92
            STZ3ZWFmZnpxYkVNZm16bVNkYWZ3d0UKAUFR1BYK4bx9JQPwqjlkVxY+fs9tI3Da
            q9lgttWVtTEtWniU8zRd9QreBjjl8NX1IQaAKi0BSLfaIODgChgv0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1afpzrwdmpec6e6ke59l5came0du04n7am3ja70krlgw6uvdj8q7shmk9qv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T12:55:41Z"
    mac: ENC[AES256_GCM,data:W5bNfJaCQTUCbUW+AHgO9SvFENxYguWNJrahp3M0BKQYIhqSDnL9s9HGXk2c1O2ZV01e1+r7iYDKcAPS0wK0zcTHLFdCVEFsu2YPcvL42sJA6Y8WEApKuQAjSLg4UnMEeYHVeNYdUAM7ZlzFeBk2fvwB8yLfL5Lixv4zSXxLIDc=,iv:Mxemiirn+fTS0HcFSmp+1dPpJnW5zgTylcAWjkioKp0=,tag:FwS/CefnOTTNVZMsV+bABg==,type:str]
    version: 3.13.3
