# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./rifqoi-com-immich.yaml
  - ./rifqoi-com-headlamp.yaml
  - ./rifqoi-com-n8n.yaml
